# 单个数组


## numpy数组的属性

In [ ]:
import numpy as np

array_1 = [[1,2,3],[5,6,7]]             # 普通的list数组
array_2 = np.array([[1,2,3],[5,6,7]])   # 使用bp.array可以将list转换为numpy的矩阵格式
print(array_2)
print("dim : ", array_2.ndim)
print("shape : ", array_2.shape)
print("size : ", array_2.size)


## numpy数组直接创建

> [numpy官方手册](https://numpy.org/doc/stable/reference/generated/numpy.array.html)

1. array
2. arange
3. linspace
4. `numpy.zeros(shape, dtype=float, order='C', *, like=None)`
5. `numpy.ones(shape, dtype=None, order='C', *, like=None)`
6. `numpy.full(shape, fill_value, dtype=None, order='C', *, like=None)`
7. `numpy.eye(N, M=None, k=0, dtype=<class 'float'>, order='C', *, like=None)`


In [ ]:
import numpy as np

# np.array
a = np.array([12,34,500],np.int)
# np.zeros
b = np.zeros((3,4))
print(b)
print(b.dtype)

## numpy从文件创建数组
- fromfile
- loadtxt

In [ ]:
import numpy as np
import matplotlib.pyplot as plt

raw_path = './dataset/test.RAW'

img = np.fromfile(raw_path,dtype=np.uint16,sep='')

img = img.reshape((1080,1920))
plt.imshow(img,cmap='gray',vmin=0,vmax=1023)
plt.show()


In [ ]:
import numpy as np 
import matplotlib.pyplot as plt

file_path = './image/frame_1_raw.txt'
width  = 100
height = 100
length = width*height

img_str = np.loadtxt(file_path,dtype=str)
img_int = np.zeros_like(img_str,dtype=np.uint8)
for i in img_str:
    img_int = np.append(img_str,i)

#size = img_in.size


# if size < length :
#     zero= np.full(length-size,0)[:,np.newaxis]
#     img = np.vstack((img_in,zero))
# else :
#     img = img_in[0:length]
# 
# img = img.reshape(height,width)
# 
# plt.imshow(img,cmap='gray',vmax=1023,vmin=0)
# plt.show()
# 
# 

## numpy单个数组操作
- clip
- max
- mix
- median
- mid
- flat
- pad
- flatten

In [ ]:
import numpy as np

a = np.arange(3,15).reshape((3,4))
# flatten()
b = a.flatten()
c = np.pad(a,((1,3),(3,1)))
print(c)

## 数组切片

In [10]:
import numpy as np 


a = np.zeros((10,10))
a[0::2,1::2] = 1
a[1::2,0::2] = 2
print(a)


[[0. 1. 0. 1. 0. 1. 0. 1. 0. 1.]
 [2. 0. 2. 0. 2. 0. 2. 0. 2. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1. 0. 1.]
 [2. 0. 2. 0. 2. 0. 2. 0. 2. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1. 0. 1.]
 [2. 0. 2. 0. 2. 0. 2. 0. 2. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1. 0. 1.]
 [2. 0. 2. 0. 2. 0. 2. 0. 2. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1. 0. 1.]
 [2. 0. 2. 0. 2. 0. 2. 0. 2. 0.]]


# 多个数组

## 数组融合meshgrid

In [ ]:
import numpy as np

x = np.arange(1,5)
y = np.arange(6,8)
xx,yy = np.meshgrid(x,y)
print('x is :')
print(x)
print('y is :')
print(y)
print('xx is :')
print(xx)
print('yy is :')
print(yy)

In [ ]:
# 生成渐变图
import numpy as np
import matplotlib.pyplot as plt

x = np.linspace(0,2**4,1920)
y = np.linspace(0,2**4,1080)
xx,yy = np.meshgrid(x,y)
img = xx*yy
img = img.astype(np.uint16)

plt.imshow(img,cmap='gray')
plt.show()


## numpy数组合并
- vstack
- hstack

In [ ]:
import numpy as np

a = np.array([1,1,1])[:,np.newaxis]
b = np.array([2,2,2])[:,np.newaxis]
print(a)
print(b)

c = np.vstack((a,b))
print(c)
d = np.hstack((a,b))
print(d)

## numpy数组分割
- split
- hsplit

In [ ]:
import numpy as np

a = np.arange(24).reshape((4,6))
print(a)
b,c = np.split(a,2)
print('sp')
print(b)
print(c)

e,f,g = np.hsplit(a,3)
print('vs')
print(e)
print(f)
print(g)

## numpy数组运算

In [ ]:
import numpy as np 

a = np.arange(10,30,2)
b = np.linspace(1,10,10)
c = a-b
d = a*b
sum = a.sum()

e = 100*np.random.random((10,5))
e_max_1 = np.max(e,axis=1)
e_max_0 = np.max(e,axis=0)
e_min= np.min(e)

## numpy矩阵运算
- 点乘
- 转置

In [ ]:
import numpy as np

a = np.arange(3,15).reshape((3,4))
# 转置
a_T = a.T
print('print : a')
print(a)
print('print : a_T')
print(a_T)

# 矩阵乘法
a_dot = np.dot(a,a_T)
print('print : a dot a_T')
print(a_dot)



In [ ]:
import numpy as np

a = np.array([[1,2,3,4,5,6,7,8,9],
                [11,12,13,14,15,16,17,18,19],
                [21,22,23,24,25,26,27,28,29],
                [31,32,33,34,35,36,37,38,39]
            ])

b = a[::2,::2]

## numpy 矩阵复制
直接使用 b=a,只是一个引用,ab的内容会一直保持一致. 修改任意一个都会同时修改两个矩阵

In [ ]:
import numpy as np 

a = np.array([1,2,3,4])
b = a
c = b

print(a)
print(b)
print(c)

a[0] = 0
print(a)
print(b)
print(c)

b = a.copy()
a[1] = 100
print(a)
print(b)
print(c)


# 注意事项

## numpy 数组数据类型转换

In [ ]:
import numpy as np 
import cv2

img1 = np.full((200,640),0,dtype=np.uint8)
img2 = np.full((200,640),200,dtype=np.uint8)
img3 = np.full((200,640),200,dtype=np.uint8)
img4 = np.full((200,640),255,dtype=np.uint8)
img = cv2.merge((img3,img2,img1))
print(img.dtype)
cv2.imshow('img',img)
cv2.waitKey(0)
cv2.destroyAllWindows()
